In [7]:
import numpy as np

# 1st 1d Array

darray = np.array([1, 2, 3, 4, 5])
print(darray)

# 2nd 2d Array
ddarray = np.array([[2,4],
                     [3,7]])
print(ddarray)

# 3rd gap

gap = np.arange(0,600,100)
print(gap)

# 4rth broadcasting
a = np.array([1,2,3,4,5])
b = np.array([10])
print(a+b)
c= np.array([1,2,3,4,5])
d= np.array([10])
print(c*d)

# 5th identity , full , float 

# floating 
list = np.array([2,4,6,8,10,12,14,16])
float_list = list.astype(float)
print(float_list)
# full 
f=np.full((1,2),8)
print(f)
# identity 
i = np.identity(7)
print(i)









[1 2 3 4 5]
[[2 4]
 [3 7]]
[  0 100 200 300 400 500]
[11 12 13 14 15]
[10 20 30 40 50]
[ 2.  4.  6.  8. 10. 12. 14. 16.]
[[8 8]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [9]:
import pandas as pd

df = pd.read_csv("sample.csv")
df = pd.head(2)
df = pd.tail(4)
df = pd.info
df = pd.describe_option

AttributeError: module 'pandas' has no attribute 'head'